### PR TITLE
Auto Dismiss the Picker if clicked outside

### PR DESCRIPTION
**Pull request by tolgaatam**
Sorry for that my text editor messed up with the tabs :/
Added a new boolean prop overlayClose, dismiss(cancel) the picker on click outside if the prop is set true

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request. Please fix the conflicts and the syntax changes.

**Comment by vinkla** [comment]
@tolgaatam what editor are you using? We've integrated an `.editorconfig` file which can fix this in your editor by default.

**Comment by tolgaatam** [comment]
i use webstorm and i guess it chose to do whatever it wants 👯‍♂️ 
whatever, i solved the conflict, it is tested and seems ready

**Comment by vinkla** [comment]
There is an [Editorconfig plugin available for WebStorm](https://plugins.jetbrains.com/plugin/7294-editorconfig). 

Please also fix the indentation. We want to keep the original indentation.

**Comment by tolgaatam** [comment]
done.

**Comment by vinkla** [comment]
@mateioprea could you please test these changes? We need a second opinion.

**Comment by puredazzle** [comment]
@tolgaatam thanks, we should also change so we have a new function that closes the instead of using `this.onPressCancel();`. Instead we should have a function called `hide` which is used in both onPressCancel and overlayDismiss

**Comment by mateioprea** [comment]
@vinkla @puredazzle yup, will test it today.

**Comment by mateioprea** [comment]
@vinkla @puredazzle yup, just tested it in an app and it works. 
Instead of ```show()``` and ```onPressCancel()``` or even a new function ```hide``` i can suggest this: 
```
triggerOverlay() {
    this.setState({
      modalVisible: !this.state.modalVisible
    })
  }
```
This should do the job :)
Thanks!

**Comment by puredazzle** [comment]
@mateioprea great! Yes that sounds good. I will make an update. Thanks for all your awesome work @mateioprea! Would you be open to becoming a contributor of this project?

**Comment by puredazzle** [comment]
@tolgaatam thanks for your PR!

**Comment by puredazzle** [comment]
I think this is a function that should always be there, ie. always close the picker on click outside of the picker. What do you think @mateioprea @tolgaatam @vinkla ?

**Comment by tolgaatam** [comment]
i assume most projects using the component will choose to enable this feature, but still letting them choose is a better option if it is documented clearly.

_Sent from my Xiaomi Redmi 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mateioprea** [comment]
@puredazzle yes, that will be awesome! :) I would love to. 
Related to your question, you can enable it by default but one should have the option to disable it. 👍

**Comment by puredazzle** [comment]
@mateioprea @tolgaatam I have updated so the user can choose to disable the overlay via props `disableOverlay` – so it is always enable until a user disables it.

**Comment by tolgaatam** [comment]
it seems pretty fair!

_Sent from my Xiaomi Redmi 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
