### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by mssureshmewara**
[Cancel/Done] Button text is not visible while iPhone X is in landscape.

### CODE REVIEW

**Comment by mateioprea** [comment]
Why did you removed the SafeAreaView ?

**Comment by mssureshmewara** [comment]
@mateioprea  Thanks for reply.
SafeAreaView is inside the model so the cancel/done text should visible in landscape mode.
If you put SafeAreaView before Model then text is not visible.
For Reference please find the screen shots.

Thanks
withchanges
without_changes

**Comment by pasalapraveen** [comment]
Dear @mateioprea,

Please commit this changes, without this changes in iPhone X Cancel/Done text is not visible fully.
For reference please check in iPhone X.

For your reference i am adding screen shot.

screen shot

Thank you.

**Comment by puredazzle** [comment]
I have merged the PR and will soon publish a new version to NPM. Thanks!

**Pull request merged**
