### PR TITLE
Add Confirm/Cancel button props style

### PR DESCRIPTION
**Pull request by mateioprea**
I think this can be useful. A client requested the fontSize to be bigger on the confirm/cancel buttons.

### CODE REVIEW

**Comment by puredazzle** [comment]
Hi @mateioprea! Thanks for your PR. It sounds good, but maybe it is better to also remove buttonColor from props and just use buttonStyle? 

It would be great if you could do a new commit where buttonColor is removed and we just use buttonStyle.

**Comment by puredazzle** [comment]
@mateioprea thanks for your PR! 

this is a great feature, and maybe it would be better to use this instead of buttonColor and remove buttonColor from the code, so all style is set via the same object `buttonStyle`. Maybe you can update your code where the user still can send in buttonColor but it will be merged before render or in render so the Text-tag only takes a single variable called `buttonStyle`.

**Comment by mateioprea** [comment]
@puredazzle so maybe instead of using buttonColor + inject in the buttonStyle, let's only use buttonStyle. It's more consistent. What do you say?

**Comment by puredazzle** [comment]
@mateioprea sounds good! could you update your PR and I'll merge.

**Comment by mateioprea** [comment]
@puredazzle done.

**Comment by puredazzle** [comment]
@mateioprea thanks!

**Comment by puredazzle** [comment]
@mateioprea I have pushed some style changes, could you please test before I publish to NPM? Thank you in advance.

**Comment by mateioprea** [comment]
Based on your commit: 

✅  - picker works
✅  - modal visible
✅  - https://www.dropbox.com/s/n02pbatgeh7azj8/Screenshot%202017-08-14%2016.04.51.png?dl=0 styles changed 

Good to go @puredazzle

**Comment by puredazzle** [comment]
@mateioprea thanks for your help! I have pushed the latest version to NPM.

**Comment by mateioprea** [comment]
Great! Will install tomorrow. Thanks!

**Pull request merged**
